In [1]:
 import pandas as pd

In [2]:
fpath = "通驰发票明细.xls"

In [3]:
df = pd.read_excel(fpath)

In [4]:
df = df[["办事处名称","发票号","数量","期数","定价","产品名称及规格"]]
df.head()

  办事处名称        发票号      数量         期数      定价          产品名称及规格
0  优线嘉兴  3393935.0  30.306  202006-03  4060.0  优线 40  Φ5.500mm
1  优线嘉兴  3393935.0  20.875  202006-03  4170.0   优线 20Cr  Φ14mm
2  优线嘉兴  3393935.0  31.874  202006-03  4160.0   优线 10B21  Φ8mm
3  优线嘉兴  3393935.0   6.837  202006-03  4160.0   优线 10B21  Φ8mm
4  优线嘉兴  3393935.0  37.323  202006-03  4010.0  优线 ZT195  Φ10mm

In [5]:
li = df["办事处名称"].tolist()

In [6]:
t = set(li)

In [7]:
t   # 注意其中的空格与nan值处理

{' ', nan, '优线南通', '优线嘉兴', '优线常州'}

In [8]:
d = pd.DataFrame({"A":["a","b","c","d"],"B":["zdz","xcy","zbx","yaz"]})

In [9]:
d

   A    B
0  a  zdz
1  b  xcy
2  c  zbx
3  d  yaz

In [10]:
l = ["a","b","c","d"]  # 先从以前的报销表中提取一个单独的业务员表，用做基准，也便于新业务员添加登记。

In [11]:
d["C"]=None
for i in d.index:
    for j in l:
        if j in d["B"].at[i]:
            d["C"].at[i]=j

In [12]:
d

   A    B  C
0  a  zdz  d
1  b  xcy  c
2  c  zbx  b
3  d  yaz  a